### ISSUE TITLE
[add feature]: Background change with cool css effects

### ISSUE THREAD

**Issue by Hunter764** [Jivanjamadar/ExpenseTracker#1]
Want to add background image and cool css effects

**Comment by Hunter764** [comment]
@Jivan052 please assign this issue to me

**Comment by Jivan052** [comment]
Hi @Hunter764 I will close issue in next 2 days. It will good if you create PR for proposed issue.

**Comment by arjunmishraaa** [comment]
@Jivan052 assign this issue to me
